import { z } from "zod";

/**
 * Self-service profile editing.
 *
 * ── THE RULE THESE SCHEMAS ENCODE ──────────────────────────────────────────
 * A field is self-editable only if it describes how to REACH or ADDRESS the
 * person. Anything that is a school record of record, or that any
 * authorisation decision reads, is not here and must not be added:
 *
 *   admissionNo / staffId  — generated by lib/ids.ts, printed on documents
 *   classId                — decides which roster and grade sheet they are on
 *   dob, gender            — collected and corrected by the office
 *   guardianName/Phone     — the guardian's data, not the student's to edit
 *   status                 — AT_RISK is derived; INACTIVE is the soft delete
 *   role, email            — email is the LOGIN IDENTITY and unique-
 *                            constrained; role is the authorisation input
 *   primarySubjectId, assignments — what a teacher may grade
 *
 * A student's `name` is deliberately absent too. It is the name printed on
 * their results and the string every staff-facing roster is sorted by, and
 * the account belongs to a minor. Staff may fix their own name; a student
 * asks the office. That is the existing policy this feature was built to
 * respect rather than quietly reverse.
 */

// Shared, so "what counts as a phone number" cannot drift between the admin
// screens (lib/validation/teacher.ts) and self-service. Loose on FORMAT by
// design — Nigerian numbers are written +234…, 0803…, and with spaces or
// dashes, and a regex tight enough to reject junk also rejects a third of
// the real ones. Length plus an allowed-character set is the honest bound.
const phone = z
  .string()
  .trim()
  .min(7, "Enter a valid phone number")
  .max(20, "That phone number is too long")
  .regex(/^[0-9+()\-\s]+$/, "Use only digits, spaces and + ( ) -");

/** ADMIN and TEACHER: the name shown on their own account. */
export const staffProfileSchema = z.object({
  name: z.string().trim().min(2, "Enter your full name").max(80, "That name is too long"),
  // Teachers only; the action ignores it for an admin, who has no Teacher row
  // to write it to. Optional here rather than in a separate schema so there
  // is one shape crossing the wire.
  phone: phone.optional(),
});

/** STUDENT: a personal contact number, and nothing else. */
export const studentProfileSchema = z.object({
  // Empty string means "clear it" — a student who gave a number may take it
  // back. Normalised to null in the action, so the column never carries ""
  // as a stand-in for absent.
  contactPhone: z.union([phone, z.literal("")]),
});

/**
 * Password change, for a user who is already signed in and NOT in the
 * first-login flow.
 *
 * Intentionally the same shape and the same three rules as
 * app/portal/first-login/actions.ts, including requiring the current
 * password. That requirement is the whole security story: without it,
 * anyone holding a live cookie — a borrowed phone, an unattended machine in
 * a school lab — could take the account over permanently. A profile page is
 * a far more obvious place to try that than the first-login screen, not a
 * less obvious one.
 */
export const passwordChangeSchema = z
  .object({
    currentPassword: z.string().min(1, "Enter your current password"),
    newPassword: z.string().min(10, "Must be at least 10 characters"),
    confirmPassword: z.string().min(1, "Confirm your new password"),
  })
  .refine((d) => d.newPassword === d.confirmPassword, {
    message: "Passwords don't match",
    path: ["confirmPassword"],
  })
  .refine((d) => d.newPassword !== d.currentPassword, {
    message: "Choose a password different from your current one",
    path: ["newPassword"],
  });

export type StaffProfileValues = z.infer<typeof staffProfileSchema>;
export type StudentProfileValues = z.infer<typeof studentProfileSchema>;
export type PasswordChangeValues = z.infer<typeof passwordChangeSchema>;
